/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as BookRoomIdRouteImport } from './routes/book.$roomId'
import { Route as ApplyRoomIdRouteImport } from './routes/apply.$roomId'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'

const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const BookRoomIdRoute = BookRoomIdRouteImport.update({
  id: '/book/$roomId',
  path: '/book/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoomIdRoute = ApplyRoomIdRouteImport.update({
  id: '/apply/$roomId',
  path: '/apply/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/properties': typeof PropertiesRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/properties': typeof PropertiesRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/properties'
    | '/admin/applications'
    | '/admin/rooms'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/applications'
    | '/admin/rooms'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/properties'
    | '/admin/applications'
    | '/admin/rooms'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PropertiesRoute: typeof PropertiesRouteWithChildren
  ApplyRoomIdRoute: typeof ApplyRoomIdRoute
  BookRoomIdRoute: typeof BookRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/book/$roomId': {
      id: '/book/$roomId'
      path: '/book/$roomId'
      fullPath: '/book/$roomId'
      preLoaderRoute: typeof BookRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$roomId': {
      id: '/apply/$roomId'
      path: '/apply/$roomId'
      fullPath: '/apply/$roomId'
      preLoaderRoute: typeof ApplyRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PropertiesRoute: PropertiesRouteWithChildren,
  ApplyRoomIdRoute: ApplyRoomIdRoute,
  BookRoomIdRoute: BookRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
