/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PayRouteImport } from './routes/pay'
import { Route as NewcomerRouteImport } from './routes/newcomer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExtrasRouteImport } from './routes/extras'
import { Route as BookRouteImport } from './routes/book'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as ApplyIndexRouteImport } from './routes/apply.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as BookRoomIdRouteImport } from './routes/book.$roomId'
import { Route as ApplyRoomIdRouteImport } from './routes/apply.$roomId'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBoardRouteImport } from './routes/admin.board'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as PropertiesIdRoomSlugRouteImport } from './routes/properties.$id.$roomSlug'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'

const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const NewcomerRoute = NewcomerRouteImport.update({
  id: '/newcomer',
  path: '/newcomer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrasRoute = ExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const BookRoomIdRoute = BookRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => BookRoute,
} as any)
const ApplyRoomIdRoute = ApplyRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => ApplyRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBoardRoute = AdminBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesIdRoomSlugRoute = PropertiesIdRoomSlugRouteImport.update({
  id: '/$roomSlug',
  path: '/$roomSlug',
  getParentRoute: () => PropertiesIdRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/extras': typeof ExtrasRoute
  '/faq': typeof FaqRoute
  '/newcomer': typeof NewcomerRoute
  '/pay': typeof PayRoute
  '/portal': typeof PortalRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transit': typeof TransitRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/book/': typeof BookIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/properties/$id/$roomSlug': typeof PropertiesIdRoomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/extras': typeof ExtrasRoute
  '/faq': typeof FaqRoute
  '/newcomer': typeof NewcomerRoute
  '/pay': typeof PayRoute
  '/portal': typeof PortalRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transit': typeof TransitRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/book': typeof BookIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/properties/$id/$roomSlug': typeof PropertiesIdRoomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/apply': typeof ApplyRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/extras': typeof ExtrasRoute
  '/faq': typeof FaqRoute
  '/newcomer': typeof NewcomerRoute
  '/pay': typeof PayRoute
  '/portal': typeof PortalRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transit': typeof TransitRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/board': typeof AdminBoardRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/apply/$roomId': typeof ApplyRoomIdRoute
  '/book/$roomId': typeof BookRoomIdRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/book/': typeof BookIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/properties/$id/$roomSlug': typeof PropertiesIdRoomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/book'
    | '/extras'
    | '/faq'
    | '/newcomer'
    | '/pay'
    | '/portal'
    | '/properties'
    | '/rooms'
    | '/sitemap.xml'
    | '/transit'
    | '/admin/applications'
    | '/admin/board'
    | '/admin/calendar'
    | '/admin/ledger'
    | '/admin/rooms'
    | '/admin/subscribers'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/admin/'
    | '/apply/'
    | '/book/'
    | '/properties/'
    | '/admin/tenants/$id'
    | '/properties/$id/$roomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/extras'
    | '/faq'
    | '/newcomer'
    | '/pay'
    | '/portal'
    | '/rooms'
    | '/sitemap.xml'
    | '/transit'
    | '/admin/applications'
    | '/admin/board'
    | '/admin/calendar'
    | '/admin/ledger'
    | '/admin/rooms'
    | '/admin/subscribers'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/admin'
    | '/apply'
    | '/book'
    | '/properties'
    | '/admin/tenants/$id'
    | '/properties/$id/$roomSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/apply'
    | '/book'
    | '/extras'
    | '/faq'
    | '/newcomer'
    | '/pay'
    | '/portal'
    | '/properties'
    | '/rooms'
    | '/sitemap.xml'
    | '/transit'
    | '/admin/applications'
    | '/admin/board'
    | '/admin/calendar'
    | '/admin/ledger'
    | '/admin/rooms'
    | '/admin/subscribers'
    | '/admin/tenants'
    | '/apply/$roomId'
    | '/book/$roomId'
    | '/properties/$id'
    | '/admin/'
    | '/apply/'
    | '/book/'
    | '/properties/'
    | '/admin/tenants/$id'
    | '/properties/$id/$roomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApplyRoute: typeof ApplyRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  ExtrasRoute: typeof ExtrasRoute
  FaqRoute: typeof FaqRoute
  NewcomerRoute: typeof NewcomerRoute
  PayRoute: typeof PayRoute
  PortalRoute: typeof PortalRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RoomsRoute: typeof RoomsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransitRoute: typeof TransitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newcomer': {
      id: '/newcomer'
      path: '/newcomer'
      fullPath: '/newcomer'
      preLoaderRoute: typeof NewcomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extras': {
      id: '/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof ExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/book/$roomId': {
      id: '/book/$roomId'
      path: '/$roomId'
      fullPath: '/book/$roomId'
      preLoaderRoute: typeof BookRoomIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/apply/$roomId': {
      id: '/apply/$roomId'
      path: '/$roomId'
      fullPath: '/apply/$roomId'
      preLoaderRoute: typeof ApplyRoomIdRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/board': {
      id: '/admin/board'
      path: '/board'
      fullPath: '/admin/board'
      preLoaderRoute: typeof AdminBoardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$id/$roomSlug': {
      id: '/properties/$id/$roomSlug'
      path: '/$roomSlug'
      fullPath: '/properties/$id/$roomSlug'
      preLoaderRoute: typeof PropertiesIdRoomSlugRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
  }
}

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBoardRoute: typeof AdminBoardRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBoardRoute: AdminBoardRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApplyRouteChildren {
  ApplyRoomIdRoute: typeof ApplyRoomIdRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyRoomIdRoute: ApplyRoomIdRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface BookRouteChildren {
  BookRoomIdRoute: typeof BookRoomIdRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookRoomIdRoute: BookRoomIdRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface PropertiesIdRouteChildren {
  PropertiesIdRoomSlugRoute: typeof PropertiesIdRoomSlugRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdRoomSlugRoute: PropertiesIdRoomSlugRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ApplyRoute: ApplyRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  ExtrasRoute: ExtrasRoute,
  FaqRoute: FaqRoute,
  NewcomerRoute: NewcomerRoute,
  PayRoute: PayRoute,
  PortalRoute: PortalRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RoomsRoute: RoomsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransitRoute: TransitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
